const assert=require('assert'),fs=require('fs'),vm=require('vm'),{performance}=require('perf_hooks'),T=require('../dist/lpk/three.min.js'),R=require('../dist/defense-rules.js');
const {parse}=require('./character-assets.cjs');T.GLTFLoader.prototype.load=function(url,ok,progress,fail){parse('dist/'+url).then(ok,fail)};
const ctx={window:{DefenseRules:R},performance,setTimeout};vm.createContext(ctx);vm.runInContext(fs.readFileSync('dist/village-navigation.js','utf8'),ctx);vm.runInContext(fs.readFileSync('dist/village-defense.js','utf8'),ctx);
const riverX=z=>-15+4*Math.sin(z*.035),depth=(x,z)=>Math.min(Math.abs(x-riverX(z))/(3+.25*Math.sin(z*.15)),Math.hypot((x+8)/12,(z+24)/14));
const height=(x,z)=>{const r=Math.max(Math.abs(x),Math.abs(z)),edge=Math.max(0,Math.min(1,(r-40)/12));const base=.12*Math.sin(x*.2)*Math.sin(z*.17)+edge*(2.6*Math.sin(x*.085+z*.045)+1.6*Math.cos(z*.12-x*.035)+.7*Math.sin(x*.21)*Math.cos(z*.16));const d=depth(x,z);if(d<1)return -1.3-.9*(1-d*d);if(d<1.35){const f=(d-1)/.35;return -1.3*(1-f)+base*f}return base};
const bridges=[8,-44].map(z=>({x:riverX(z),z})),bridge=(x,z)=>bridges.some(b=>Math.abs(x-b.x)<5&&Math.abs(z-b.z)<1.7);
const world=new T.Group(),objects=[];for(const[x,z]of [[-1,17],[10,24],[22,15],[28,2],[23,-12],[11,-20],[3,-9],[30,26],[18,34]]){const root=new T.Group(),m=new T.Mesh(new T.BoxGeometry(5,3,5),new T.MeshBasicMaterial());m.position.y=1.5;root.position.set(x,height(x,z),z);root.add(m);world.add(root);objects.push(root)}world.updateMatrixWorld(true);
const navigation=ctx.window.createVillageNavigation(T,{revision:()=>1,ground:height,objects:()=>objects,forest:()=>[],water:(x,z)=>depth(x,z)<1&&!bridge(x,z),bridge:(x,z)=>bridge(x,z)?.08:null});
const game={phase:'day',screen:'game',settings:{difficulty:'Сказ'},hero:{hp:5,hpMax:5,stats:{str:3},learnedSkills:['strike'],bag:[],scenePosition:{x:1.8,z:-2}},resources:{silver:10},buildings:{tower:0},ui:{},story:{},domovoy:{},villagers:[{id:'marfa'}]};R.ensure(game);let enabled=true,changed=0,victories=0;const p=new T.Vector3(1.8,height(1.8,-2),-2),warrior={ready:()=>true,position:()=>p,order:()=>{},strike:(p,impact)=>{impact?.();return true}};
const controller=ctx.window.createVillageDefense(T,world,{state:()=>game,warrior:()=>warrior,navigation,ground:height,material:()=>{},enabled:()=>enabled,changed:()=>changed++,persist:()=>{},victory:()=>victories++,defeat:()=>{}});
(async()=>{for(let wave=1;wave<=3;wave++){const began=performance.now(),seeds=await controller.prepare(wave);assert.equal(seeds.filter(e=>e.kind!=='leshy').length,R.count(wave,'Сказ'));assert.equal(seeds.filter(e=>e.kind==='leshy').length,1);console.log('wave',wave,'connected spawns',seeds.length,'planning ms',Math.round(performance.now()-began));}
const seeds=[{id:'near',x:p.x+1,z:p.z,spawnX:p.x+1,spawnZ:p.z,hp:3,maxHp:3}];assert(R.begin(game,seeds));controller.sync();assert.equal(controller.roots().length,1);enabled=false;controller.tick(1);assert.equal(game.defense.elapsed,0);assert.equal(game.hero.hp,5);enabled=true;controller.select('near');controller.attack();assert.equal(seeds[0].hp,1);game.defense.attackCooldown=0;controller.attack();assert.equal(seeds[0].hp,0);assert.equal(victories,1);assert.equal(controller.roots().length,0);assert.equal(game.phase,'waveDialogue');console.log('PASS real Three.js pawn geometry, connected spawn planning around houses/river via bridges, paused simulation, enemy selection/hit, actor removal and one victory');})().catch(e=>{console.error(e);process.exitCode=1});
